import './bootstrap';
import 'bootstrap/dist/js/bootstrap';
import './script';
import '@fortawesome/fontawesome-free/js/all';
import './cards_carousel';
import './my_button';
import './counter';
import './show';
import './tronco';
